madmaze/pytesseract

src/pytesseract.py

The config argument for run_tesseract() doesn't currently work properly. It gives tesseract a single string, which tesseract can't recognize, and so the config options aren't implemented. A simple shlex.split() fixes that by splitting the config argument into individual strings and putting them to a list. I.e., run_tesseract(foo.png, bar, config="-psm 8 nobatch letters") will pass ["-psm", "8", "nobatch", "letters"] to tesseract, instead of ["-psm 8 nobatch letters"].
Please consider a commit, or another solution to this problem.

Allows tesseract to implement config options

---

README.md
setup.py
src/__init__.py
src/pytesseract.py

Hi,
These changes make the library running with Python 2 and 3. I think the commit messages are self-explanatory. So please test it and consider to merge it.

Add Python 3 support without droping Python 2 support

---

src/pytesseract.py

Just nitpicking. The file is called 'pytesseract.py' not 'tesseract.py', as mentioned in the usage message.

Fix 'usage' message

---

src/pytesseract.py

If Tesseract produces non-ascii output, pytesseract blows up when trying
to read the output file.
This commit forces pytesseract to treat Tesseract's output 1) as a binary file
type and 2) as UTF-8 encoded.
```
File ".../vault/vault/libs/ocr_document/ocr_document.py", line 80, in ocr_segment
extracted_text = pytesseract.image_to_string(cropped_pil_image)
File ".../venv/lib/python3.4/site-packages/pytesseract/pytesseract.py", line 167, in image_to_string
return f.read().strip()
File ".../venv/lib/python3.4/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 21: ordinal not in range(128)
```

Decode tesseract's output as UTF-8

---

README.rst
src/__init__.py
src/pytesseract.py

I had a project that required getting confidence values for the Tesseract run and saw that this library didn't support tsv files, so here's a proposal for a feature that I think will add a lot of value for users. The tsv file contains information about box positions/sizes, line and page numbers, and confidences, as well as providing the text. 
While this update to pytesseract is compatible with Python 2.4+ the tsv feature only exists in tesseract 3.05+
Current output:
```
level	page_num	block_num	par_num	line_num	word_num	left	top	width	height	conf	text
1	1	0	0	0	0	0	0	600	103	-1	
2	1	1	0	0	0	23	26	555	51	-1	
3	1	1	1	0	0	23	26	555	51	-1	
4	1	1	1	1	0	23	26	555	22	-1	
5	1	1	1	1	1	23	26	44	17	86	This
5	1	1	1	1	2	76	26	15	17	86	is
5	1	1	1	1	3	99	30	57	13	86	some
5	1	1	1	1	4	164	26	42	21	73 …
```

Added verbose option that returns detailed output from tesseract run

---

src/__init__.py
src/pytesseract.py

Gives users the option between three return value types:
- String
- Dictionary
- Byte data (This could help with https://github.com/madmaze/pytesseract/issues/86) 
Default output type is Output.STRING
Usage:
```
>>> from PIL import Image
>>> import pytesseract
>>> from pytesseract import Output
>>> print(pytesseract.image_to_string(Image.open('test.png'), output_type=Output.BYTES))
b'This is some text, written in Arial, that will be read by\nTesseract. Here are some symbols: !@#$%"&\xe2\x80\x98()\n\n'
```

Output types

---

src/pytesseract.py

Pytesseract is not currently using any enum features, so it's not necessary to extend the Enum class. This should make it compatible with Python versions earlier than 3.4. 
Also, fixed bug that occurs when TSV files do not have any "text" found in the last row and last row is shorter than the preceding rows.

Remove enum dependency, fix bug with missing text in last line

---

src/pytesseract.py

To be able to run pytesseract from a standalone executable without a console created by pyinstaller I had to use proc = subprocess.Popen(command, **subprocess_args(True)) with subprocess_args from https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess, whereas e-dul's fix didn't work. Moreover subprocess_args seems to be written in a way that is not platform specific.

Fixing subprocess call for standalone pyinstaller exectuables without console

---

src/__init__.py
src/pytesseract.py

I've implemented the `image_to_osd` function to get the output of a Tesseract execution with `--psm 0`, because I saw that it didn't worked with the other functions.
I've preferred to insert a new function instead of adding this functionality to `image_to_string` because the ouput is very different to a normal Tesseract execution, especially with a dictionary as output, where I thought it was better to create one with the OSD parameters, that's why I've created the `osd_to_dict` function.

image_to_osd function

---

src/pytesseract.py

Replace `StringIO` by `BytesIO` because it file.read() return bytes and not strings in `image_to_data`
Sorry about that

Replace StringIO by BytesIO in image_to_data

---

dev-requirements.txt

See https://github.com/PyCQA/pep8-naming#plugin-for-flake8 to the list of additional checks this plugin adds to `flake8`.
The current code all complied, so no code changes were needed.

Add pep8-naming plugin to pep8 tox env

---

.travis.yml

This will actually produce Travis builds once #190 is performed by a project maintainer.

Create Travis CI config

---

dev-requirements.txt

`flake8-quotes` will validate that strings use consistent quote style (`'` as used in this project) and that docstrings conform to PEP 257 quote style.
The actual project didn't need any fixes, this will just ensure that the style doesn't regress.

Validate string quote style

---

README.rst

Some (currently all) of `pytesseract`'s test suite requires that `tesseract` is installed, so remind the user of this.

Add testing section clarification about needed tesseract in PATH

---

src/pytesseract.py

This pull request closes the open file descriptor returned by `tempfile.mkstemp`. Without this change, I believe pytesseract leaks open file descriptors every time it is called.
Quoting from the documentation:
> mkstemp() returns a tuple containing an OS-level handle to an open file (as would be returned by os.open()) and the absolute pathname of that file, in that order.
A script I ran to process frames of a long video eventually terminated due to `OSError: [Errno 24] Too many open files`, and `lsof` also showed the number of open files steadily increasing. After making this change, the problem has gone away, and `lsof` also indicates that we're no longer leaking file descriptors.

Close temp file descriptor

---

src/pytesseract.py
tests/test_pytesseract.py

Allow bubbling up all non-pytesseract related OSError exception.
Fixes #228 - check the issue for more details.

Proper handling of OSError exceptions

---

src/pytesseract.py

Raising RuntimeError properly, instead of shadowing it in favor of TesseractError.
The problem was that even if we kill the tesseract process, it still sends some text to stderr.
I we made incorrect assumption, when developing the timeout feature - that the stderr will be empty, when we try to kill the process, while the OCR process is running.

Fix the handling for the timeout feature

---

src/pytesseract.py

In `save` func, `input_file_name` is parsed and used in `format` kwarg to save the image. Image.info already has `format`key
This causes  `multiple values for keyword argument 'format'` error
PIL==6.2.1
pytesseract==0.3.1

delete format kwarg

---

src/__init__.py
src/pytesseract.py
tests/pytesseract_test.py

Mentioned in #234 
Tesseract has supported ALTO XML for over a year now, since 4.1.0. This pull request implements the function `image_to_alto_xml`, which returns ALTO XML as bytes. An exception is thrown if the Tesseract version is too old.
Tested with Tesseract versions:
4.0.0-beta.1 (Ubuntu 18.04): throws exception as excepted
4.1.1 (Ubuntu 20.04): works as expected
5.0.0-alpha-771-g7498 (recent development version built from source): works as expected

Add support for outputting ALTO XML (>=4.1.0)

---

pytesseract/pytesseract.py

This is a possible solution for a bug on method 'file_to_dict' on pytesseract.py (line 303). An error comes up when ```rows``` has length 1. After ```rows.pop(0)```, ```rows``` become an empty list and the code crashes on the following lines.

fixing bug on method 'file_to_dict'

---

pytesseract/pytesseract.py

When I converted my ML solution to one file executable without console mode via pyinstaller pytesseract was not working. There was a subprocess problem. Problem was solved in this [issue](pyinstaller/pyinstaller#5601). I have updated the code for preventing future problems.

Pyinstaller non-console problem is solved.

---

setup.cfg

Universal wheels are used to target both Python 2 and Python 3. Since this package targets Python 3.7+, this is no longer appropriate.

Remove Python 2-specific universal wheel specification

---

README.rst

The current link to the TSV usage is dead, the new link shows an example of TSV in action in the current tesseract documentation.

Fix dead link to TSV usage info

---

README.rst

- After checking the `python-imaging` and `python3-imaging` packages in Debian/Ubuntu, it seems that the package names are changed.
- When running the `` command, some related log outputs are as follows:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python3-imaging is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
python3-pil:i386 python3-pil
E: Package 'python3-imaging' has no installation candidate
......
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python-imaging is not available, but is referred to by another package.
This may …
```

Fix the correct imaging package in Debian/Ubuntu

---

pytesseract/pytesseract.py

This change adds debug logging to see which CLI arguments *pytesseract* passes to Tesseract itself. The goal is to simplify debugging reported issues, especially as most of them turn out to be related to plain Tesseract anyway, fixing the first part of #456.
```python3
import pytesseract
import logging
logging.basicConfig(level=logging.WARNING)
logging.getLogger('pytesseract').setLevel(logging.DEBUG)
image = '/home/stefan/Desktop/file.png'
print(pytesseract.image_to_string(image))
```
```bash
DEBUG:pytesseract:['tesseract', '/home/stefan/Desktop/file.png', '/tmp/tess_0kncj5u3', 'txt']
This is my text.
```

Add debug logging for CLI arguments

---

README.rst
pytesseract/__init__.py
pytesseract/pytesseract.py
tests/pytesseract_test.py

This PR resolves #304 by adding a new function `run_and_get_multiple_output` that can take multiple extensions (output formats) and return them after one invocation of `tesseract`. This saves compute time when the user tries to get multiple outputs from one input, e.g., 
```python
text, pdf = run_and_get_multiple_output(image, extensions=['txt', 'pdf'])
```
The main addition in this PR is the function `run_and_get_multiple_output`. It accepts a list of extensions like `['pdf', 'txt']`. Internally this function:
1. assembles the command line config arguments needed by mapping each extension to its required config arguments (stored as a constant in `EXTENTION_TO_CONFIG`).
2. invokes `tesseract` just once to generate all the files needed
3. for each extension load its result and return in …

allow multiple output

---

.github/workflows/ci.yaml

Updates:
- Test the installation of the commit/PR (the version we checked out with actions/checkout) instead of testing the default branch of the repo. With this, we can actually test pull requests.
- Test all commits and PRs regardless of branch name.
- Add option to dispatch the workflow manually.

Improve and fix CI
