setup.py, src/pytesseract.py
It would be nicer with proper error messages but hey, it's something ;)
=> added entry point for console script to setup.py

src/pytesseract.py
Fixed a small spelling mistake.
=> Fixed a typo in line #131

setup.py
with it pip will be able to install Pillow automatically
=> setup.py Add Pillow as a dependency

src/pytesseract.py
Changed the current method that uses split with the faster convert
method within PIL Image object
=> Improved method to discard alpha channel

src/pytesseract.py
=> fixes setting config overwriting essential tsv parameter

src/pytesseract.py
See https://www.python.org/dev/peps/pep-0257/
=> Make docstrings PEP 257 compliant

.gitignore
This makes for a more pleasant experience for contributors using [PyCharm](https://www.jetbrains.com/pycharm/).
=> Ignore PyCharm project settings

src/pytesseract.py
This docstring was missed in #191
=> Fix last docstring to conform to PEP 257

README.rst
=> Add Travis build status badge

.travis.yml
Please see the related issue https://github.com/madmaze/pytesseract/issues/216.
=> Update `tesseract-ocr` for testing

setup.py, src/pytesseract.py, tests/test_pytesseract.py
Fixes #220 and adds unit test for the numpy array case.
=> Refactoring and fixing image format (extension) handling

LICENSE, README.rst, setup.py
Changing the license of this repository according to the vote from #237 (Petition to change license to Apache 2.0 (to match tesseract-ocr)).
Resolves #237
=> License change to Apache License Version 2.0

src/pytesseract.py, tests/pytesseract_test.py
As per discussion on #272 & #273.
=> Add README hint to error message

pytesseract/pytesseract.py, tests/pytesseract_test.py
=> Fix handling for invalid tesseract version

pytesseract/pytesseract.py
@int3l,
this fix normalized the behavior related in the issue #355.
=> Fix timeout_manager

pytesseract/pytesseract.py
=> Fix default hocr config

pytesseract/pytesseract.py, tests/pytesseract_test.py
=> Add uncached tesseract version call

.github/workflows/ci.yaml, setup.cfg
Axe testing for Python 3.7
Add testing for Python 3.11
Fixes #484
=> Upgrade the CI environment

.github/workflows/ci.yaml, pytesseract/pytesseract.py, setup.cfg
=> Add support for python 3.12

pytesseract/pytesseract.py
updated to accept numbers in traineddata files.
=> fix issue #552 regex
